# Generated by Django 3.2 on 2022-09-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=100)),
                ('service_location', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_address', models.TextField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Actioned')], default=0)),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
    ]
