# Generated by Django 3.2 on 2022-09-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
