# Generated by Django 3.2 on 2022-09-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Shipped'), (2, 'Completed'), (3, 'Hold'), (4, 'Cancelled')], default=0),
        ),
    ]
